name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v1
      - name: install dependencies
        run: yarn install
      - name: generate app.
        run: yarn build
      - name: Publish to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: build
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
